# Generated by Django 4.2.5 on 2023-09-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=1, max_digits=20)),
                ('height', models.DecimalField(decimal_places=1, max_digits=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
