# Generated by Django 4.2.5 on 2023-09-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserUpload',
            new_name='UserImages',
        ),
    ]
