# Generated by Django 4.2.5 on 2023-09-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_rename_userupload_userimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImages',
        ),
    ]
